### ISSUE TITLE
Is it possible to export IGES,STEP using zmesh package ?

### ISSUE THREAD

**Issue by selvakarna** [seung-lab/zmesh#11]
Is it possible to export IGES,STEP using zmesh package ?

**Comment by william-silversmith** [comment]
Hi Selvakarna,

It looks to me like STEP and IGES are CAD formats. Most CAD programs can
convert the OBJ files zmesh outputs into one of those formats.

Will

**Comment by selvakarna** [comment]
is there way is possible or not? Surface to IGES/STEP ?

**Comment by william-silversmith** [comment]
Not directly through this package. You can export an obj but you'll need
another program to do the converstion to STEP

**Comment by selvakarna** [comment]
@william-silversmith , can you share step conversion from obj , support package and python sample code?

**Comment by selvakarna** [comment]
@william-silversmith  , can you  share sample code?

**Comment by william-silversmith** [comment]
I'm sorry I've never done it and it's not supported by this package. :( Try
looking into a CAD program and see if it has tools for performing the
conversion from obj.

**Comment by william-silversmith** [comment]
I'm going to close this as resolved as it is unrelated to zmesh functions and the obj conversion route has been discussed.
